name: $name
version: $version
description: $description
author: iAngry
main: me.iangry.trollingfreedom.main.Core
softdepend: [Essentials, Citizens, ProtocolLib]
api-version: $apiVersion
commands:
  trollingfreedom:
    description: Plugin help
    aliases: [ tf ]
  trollgui:
    descrption: Troll GUI open
    aliases: [tgui, trollingfreedomgui, tfgui]
  untroll:
    description: Untroll player
    aliases: [ stoptroll ]
  trollp:
    description: Troll with CMD
  control:
  test: